version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./crm:/var/www/html/crm
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5433
      - POSTGRES_DB=crm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
